In [3]:
import numpy as np
import pandas as pd

### 1. Initialize k centroids. Here note down centroids is from our actual data point, no any dreamy concept.

In [4]:


# Step 1: Randomly place boxes (initialize centroids)
def initialize_centroids(X, k):
    n_samples, _ = X.shape
    random_indices = np.random.choice(n_samples, k, replace=False) ## here we chhose index randomly
    centroids = X[random_indices] ## here we get data through the index.
    return centroids

# Step 2: Assign toys to boxes
def assign_to_clusters(X, centroids):
    clusters = []
    for point in X:
        distances = [np.linalg.norm(point - centroid) for centroid in centroids]
        cluster = np.argmin(distances)
        clusters.append(cluster)
    return np.array(clusters)

# Step 3: Move boxes to the center of assigned toys (update centroids)
def update_centroids(X, clusters, k):
    centroids = []
    for i in range(k):
        cluster_points = X[clusters == i]
        centroid = np.mean(cluster_points, axis=0)
        centroids.append(centroid)
    return np.array(centroids)

# K-means algorithm
def kmeans(X, k, max_iters=100):
    # Step 1:- Initialize Centroids
    centroids = initialize_centroids(X, k) # here X is our data, k is number of cluster which we want
    
    for _ in range(max_iters):
        clusters = assign_to_clusters(X, centroids)
        new_centroids = update_centroids(X, clusters, k) ## now we get 2 new centroids which is dreammy.(not actual data point)

        if np.all(centroids == new_centroids):
            break
        centroids = new_centroids
    return clusters, centroids

# Toy example
X = np.array([[1, 2], [2, 3], [8, 7], [7, 8], [9, 10]])
k = 2
clusters, centroids = kmeans(X, k)
print("Final clusters:", clusters)
print("Final centroids:", centroids)


Final clusters: [1 1 0 0 0]
Final centroids: [[8.         8.33333333]
 [1.5        2.5       ]]


In [21]:
# Understanding of data
X = np.array([[1, 2], [2, 3], [8, 7], [7, 8], [9, 10]])
df = pd.DataFrame(X, columns=['features', 'target'])
df ## here may be you have one or more features but it work as same.

features  target
0         1       2
1         2       3
2         8       7
3         7       8
4         9      10

In [24]:
def initialize_centroids(X, k):
    n_samples, _ = X.shape
    random_indices = np.random.choice(n_samples, k, replace=False) ## here we chhose index randomly
    centroids = X[random_indices] ## here we get data through the index.
    return centroids

def assign_to_clusters(X, centroids):
    clusters = []
    for point in X:
        distances = [np.linalg.norm(point - centroid) for centroid in centroids] # this function gives you distance from point to clusters.
        print(distances) 
        cluster = np.argmin(distances)
        print("This is cluster:- \n", cluster)
        print("-----------------------------")
        clusters.append(cluster)
    print("This is full clusters", clusters)
    return np.array(clusters)

def update_centroids(X, clusters, k):
    centroids = []
    for i in range(k):
        cluster_points = X[clusters == i]
        print("This is cluster points:- ", cluster_points)
        centroid = np.mean(cluster_points, axis=0)
        print("this is our shit new centroid through mean:- ", centroid)
        centroids.append(centroid)
    print("Our new centorids which is DREAMMY:- ", centroids)
    return np.array(centroids)

In [25]:
centroids = initialize_centroids(X, 2)
centroids

clusters = assign_to_clusters(X, centroids) ## here you can see each data point assign to its nearest cluster.
update_centroids(X, clusters, 2)

[8.48528137423857, 11.313708498984761]
This is cluster:- 
 0
-----------------------------
[7.0710678118654755, 9.899494936611665]
This is cluster:- 
 0
-----------------------------
[1.4142135623730951, 3.1622776601683795]
This is cluster:- 
 0
-----------------------------
[0.0, 2.8284271247461903]
This is cluster:- 
 0
-----------------------------
[2.8284271247461903, 0.0]
This is cluster:- 
 1
-----------------------------
This is full clusters [0, 0, 0, 0, 1]
This is cluster points:-  [[1 2]
 [2 3]
 [8 7]
 [7 8]]
this is our shit new centroid through mean:-  [4.5 5. ]
This is cluster points:-  [[ 9 10]]
this is our shit new centroid through mean:-  [ 9. 10.]
Our new centorids which is DREAMMY:-  [array([4.5, 5. ]), array([ 9., 10.])]


array([[ 4.5,  5. ],
       [ 9. , 10. ]])

In [26]:
X

array([[ 1,  2],
       [ 2,  3],
       [ 8,  7],
       [ 7,  8],
       [ 9, 10]])

In [28]:
clusters

array([0, 0, 0, 0, 1], dtype=int64)

In [27]:
for i in range(2):
    print(X[clusters == i])

[[1 2]
 [2 3]
 [8 7]
 [7 8]]
[[ 9 10]]
