In [3]:
import numpy as np
import pandas as pd

In [22]:
np.arange(2,3,0.055)

array([2.   , 2.055, 2.11 , 2.165, 2.22 , 2.275, 2.33 , 2.385, 2.44 ,
       2.495, 2.55 , 2.605, 2.66 , 2.715, 2.77 , 2.825, 2.88 , 2.935,
       2.99 ])

In [23]:
np.linspace(2,3,100)

array([2.        , 2.01010101, 2.02020202, 2.03030303, 2.04040404,
       2.05050505, 2.06060606, 2.07070707, 2.08080808, 2.09090909,
       2.1010101 , 2.11111111, 2.12121212, 2.13131313, 2.14141414,
       2.15151515, 2.16161616, 2.17171717, 2.18181818, 2.19191919,
       2.2020202 , 2.21212121, 2.22222222, 2.23232323, 2.24242424,
       2.25252525, 2.26262626, 2.27272727, 2.28282828, 2.29292929,
       2.3030303 , 2.31313131, 2.32323232, 2.33333333, 2.34343434,
       2.35353535, 2.36363636, 2.37373737, 2.38383838, 2.39393939,
       2.4040404 , 2.41414141, 2.42424242, 2.43434343, 2.44444444,
       2.45454545, 2.46464646, 2.47474747, 2.48484848, 2.49494949,
       2.50505051, 2.51515152, 2.52525253, 2.53535354, 2.54545455,
       2.55555556, 2.56565657, 2.57575758, 2.58585859, 2.5959596 ,
       2.60606061, 2.61616162, 2.62626263, 2.63636364, 2.64646465,
       2.65656566, 2.66666667, 2.67676768, 2.68686869, 2.6969697 ,
       2.70707071, 2.71717172, 2.72727273, 2.73737374, 2.74747

In [30]:
arr1 = np.array([1,2,3,4,5])
# arr2 = np.array([6,7,8,9,10])
arr2 = np.array([2])

arr1+arr2

array([3, 4, 5, 6, 7])

In [69]:
arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2 = np.array([[1,2],[3,4],[5,6]])
arr3 = np.array([[7,5,7],[8,3,4],[9,4,5]])

arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
new_arr = np.array([[arr1[1][1], arr1[1][2]], [arr1[2][1], arr1[2][2]]])
new_arr

array([[5, 6],
       [8, 9]])

In [85]:
print(arr1+arr3)

[[ 8  7 10]
 [12  8 10]
 [16 12 14]]


In [80]:
arr1-arr3

array([[-6, -3, -4],
       [-4,  2,  2],
       [-2,  4,  4]])

In [81]:
arr1*arr3

array([[ 7, 10, 21],
       [32, 15, 24],
       [63, 32, 45]])

In [86]:
arr1+4

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [95]:
odd_find= np.arange(1,20)
odd_find[1::2]
odd_find[-1]

19

In [99]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
arr1[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [114]:
arr1[0:2:][0][2]

3

In [120]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [121]:
arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2 = np.array([[1,2],[3,4],[5,6]])
arr3 = np.array([[7,5,7],[8,3,4],[9,4,5]])

In [125]:
np.add(arr1, arr3)

array([[ 8,  7, 10],
       [12,  8, 10],
       [16, 12, 14]])

In [149]:
doc_arr=[]

In [166]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

In [167]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [177]:
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [199]:
arr4 = np.array([[1,2,3,4],[5,6,7,8],[4,6,3,7]])

In [200]:
arr4.shape

(3, 4)

In [201]:
arr4.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 4],
       [6, 3, 7]])

In [195]:
np.arange(16).reshape((4, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [208]:
eye = np.eye(4, dtype='i')
eye[0][0] = 2
eye

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [209]:
identity = np.identity(4, dtype='i')
identity[0][0] = 2
identity

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

### Assignment question

In [214]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [216]:
np.array(['a','e','i','o','u'])

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [221]:
np.linspace(1,1,10, dtype='i').reshape(2,5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [230]:
np.ones((2,5), dtype='i')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [235]:
myarray1 = np.array([[2.7,2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray1

array([[  2.7,   2. , -19. ],
       [  0. ,   3.4,  99.9],
       [ 10.6,   0. ,  13. ]])

In [264]:
myarray2 = np.arange(4,64,4, dtype='f').reshape((3,5))
myarray2

array([[ 4.,  8., 12., 16., 20.],
       [24., 28., 32., 36., 40.],
       [44., 48., 52., 56., 60.]], dtype=float32)

In [294]:
myarr = np.linspace(4,64,15, dtype=int).reshape(3,5)
myarr

array([[ 4,  8, 12, 16, 21],
       [25, 29, 34, 38, 42],
       [46, 51, 55, 59, 64]])